### ISSUE TITLE
database error in oneops 

### ISSUE THREAD

**Issue by Reddyvedanth** [oneops/oneops-cla#22]
Please correct the following errors:
### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: Date out of range. Fix the cm_ci_log_insert() function! Where: SQL statement "insert into cm_ci_log(log_id, log_time, log_event, ci_id, ci_name, class_id, class_name, comments, ci_state_id, ci_state_id_old) values ...

**Comment by rashisha** [comment]
facing the similar issue using AWS AMI

**Comment by frellnet** [comment]
I am facing the same issue with ami-611c8276

**Comment by rashisha** [comment]
oneops AMIs available in AWS were built with old DB schema( long back Aug 2016).  This schema didn’t have support for Year 2017. 
This is the reason for the above DB failure. Latest schema is available in the URL: https://github.com/oneops/db-schema
